export const projects = [
    {
        name: "SGQueue",
        link: null,
        githubLink: "https://github.com/mrshabel/sgqueue",
        about: "A lightweight, reliable postgres-based message queue with exactly-once-delivery guarantees.",
        stack: ["Go", "PostgreSQL", "Message Queues"],
        selected: true,
        duration: "2025",
    },
    {
        name: "SGBank",
        link: null,
        githubLink: "https://github.com/mrshabel/sgbank",
        about: "A general ledger banking system for handling transactions between accounts, implementing financial transaction processing and account management.",
        stack: ["Go", "Gin"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Gumlog",
        link: null,
        githubLink: "https://github.com/mrshabel/gumlog",
        about: "A highly durable distributed commit log service implementing Raft algorithm for distributed consensus and gRPC communication, showcasing distributed systems and high-performance data handling.",
        stack: [
            "Go",
            "gRPC",
            "RAFT",
            "Protocol Buffers",
            "Distributed Systems",
        ],
        selected: true,
        duration: "2024",
    },
    {
        name: "Shache",
        link: null,
        githubLink: "https://github.com/mrshabel/shache",
        about: "A lightweight, thread-safe TTL-based caching service built in Go.",
        stack: ["Go", "Caching"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Gorr",
        link: null,
        githubLink: "https://github.com/mrshabel/gorr",
        about: "A reverse proxy that routes HTTP requests to multiple upstream services based on URL prefix patterns.",
        stack: ["Go", "Reverse Proxy"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Ask Shabel",
        link: "https://ask-shabel.vercel.app",
        githubLink: "https://github.com/mrshabel/ask-shabel",
        about: "A sophisticated chat AI application powered by OpenAI's API, featuring natural language processing, context-aware responses, and a modern UI built with Next.js and Shadcn/UI.",
        stack: ["React", "Next.js", "Shadcn/UI", "Tailwind CSS", "OpenAI"],
        selected: true,
        duration: "2023 – Present",
    },
    {
        name: "Auth Service",
        link: null,
        githubLink: "https://github.com/mrshabel/auth-service",
        about: "A robust authentication service implementing JWT, OAuth2, and RBAC. Features include user management, role-based access control, and secure token handling.",
        stack: ["TypeScript", "Node.js", "Express.js", "Docker", "PostgreSQL"],
        selected: false,
        duration: "2024",
    },
    {
        name: "Notification Service",
        link: null,
        githubLink: "https://github.com/mrshabel/notification-service",
        about: "A scalable notification service built with FastAPI and RabbitMQ, supporting multiple notification channels and real-time delivery.",
        stack: ["Python", "FastAPI", "RabbitMQ", "Docker", "Nginx"],
        selected: true,
        duration: "2024",
    },
    {
        name: "Rate Limiter",
        link: null,
        githubLink: "https://github.com/mrshabel/rate-limiter",
        about: "A distributed rate limiting solution using Redis for high-performance request throttling and protection against API abuse.",
        stack: ["TypeScript", "Node.js", "Redis", "PostgreSQL", "Docker"],
        selected: false,
        duration: "2024",
    },
    {
        name: "Beckyplus Commerce",
        link: "https://beckyplus.vercel.app",
        githubLink: "https://github.com/mrshabel/beckyplus-commerce",
        about: "A full-featured e-commerce platform with product management, cart functionality, and secure checkout process.",
        stack: ["React", "Tailwind CSS", "Chakra UI", "Supabase"],
        selected: false,
        duration: "2023 – Present",
    },
    {
        name: "URL Shortener System",
        link: null,
        githubLink: "https://github.com/mrshabel/url-shortener",
        about: "A complete URL shortening system with both backend API and frontend client, featuring analytics and custom short URLs.",
        stack: ["TypeScript", "Next.js", "Node.js", "Express.js", "PostgreSQL"],
        selected: false,
        duration: "2024",
    },
];
