export const projects = [
    {
        name: "Ask Shabel",
        link: "https://ask-shabel.vercel.app",
        githubLink: "https://github.com/mrshabel/ask-shabel",
        about: "A chat AI application powered by OpenAI’s API, enabling natural language processing and context-aware responses.",
        stack: ["React", "Next.js", "Shadcn/UI", "Tailwind CSS", "OpenAI"],
        selected: true,
        duration: "2023 – Present",
    },
    {
        name: "Notification Service",
        link: null,
        githubLink: "https://github.com/mrshabel/notification-service",
        about: "A service for efficiently managing and delivering notifications.",
        stack: ["Python", "FastAPI", "RabbitMQ", "Docker", "Nginx"],
        selected: true,
        duration: "2024",
    },
    {
        name: "Auth Service",
        link: null,
        githubLink: "https://github.com/mrshabel/auth-service",
        about: "A robust authentication service supporting secure authentication, authorization, and RBAC.",
        stack: ["TypeScript", "Node.js", "Express.js", "Docker"],
        selected: true,
        duration: "2024",
    },
    {
        name: "Rate Limiter",
        link: null,
        githubLink: "https://github.com/mrshabel/rate-limiter",
        about: "A rate-limiting solution to safeguard APIs from abuse.",
        stack: ["TypeScript", "Node.js", "Redis", "PostgreSQL", "Docker"],
        selected: true,
        duration: "2024",
    },
    {
        name: "Beckyplus Commerce",
        link: "https://beckyplus.vercel.app",
        githubLink: "https://github.com/mrshabel/beckyplus-commerce",
        about: "An e-commerce platform developed to enhance online shopping experiences.",
        stack: ["React", "Tailwind CSS", "Chakra UI", "Supabase"],
        selected: false,
        duration: "2023 – Present",
    },
    {
        name: "URL Shortener",
        link: null,
        githubLink: "https://github.com/mrshabel/url-shortener",
        about: "A backend API for generating and managing shortened URLs.",
        stack: ["TypeScript", "Node.js", "Express.js"],
        selected: false,
        duration: "2024",
    },
    {
        name: "URL Shortener Client",
        link: null,
        githubLink: "https://github.com/mrshabel/url-shortener-client",
        about: "A frontend client for interacting with a URL shortening service.",
        stack: ["TypeScript", "Next.js"],
        selected: false,
        duration: "2024",
    },
];
