export const projects = [
    // selected projects
    {
        name: "BeckDB",
        link: "https://docs.google.com/document/d/1JraaGk-bAUwHib3XfE5EUJxWVKODEQ7cPCapDtRG-WE/edit?usp=sharing",
        githubLink: "https://github.com/mrshabel/beckdb",
        about: "A high-performance key-value store built from the ground up, inspired by the Bitcask paper and featuring a Redis-compatible server.",
        stack: ["Go", "Database Internals", "Redis Protocol"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Gumlog",
        link: null,
        githubLink: "https://github.com/mrshabel/gumlog",
        about: "A fault-tolerant, in-memory distributed cache that uses Raft to keep data consistent across a cluster, eliminating single points of failure.",
        stack: ["Go", "gRPC", "RAFT", "Serf", "Distributed Systems"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Shache",
        link: null,
        githubLink: "https://github.com/mrshabel/shache",
        about: "A fault-tolerant, in-memory distributed cache that uses Raft to keep data consistent across a cluster, eliminating single points of failure.",
        stack: ["Go", "Distributed Systems", "Raft"],
        selected: true,
        duration: "2025",
    },
    {
        name: "KRON",
        link: null,
        githubLink: "https://github.com/mrshabel/kron",
        about: "A distributed, fault-tolerant cron system that leverages Kafka to schedule and process tasks across multiple nodes, solving the single-point-of-failure problem of traditional cron.",
        stack: ["Go", "Kafka", "Cron", "Distributed Systems"],
        selected: true,
        duration: "2025",
    },
    {
        name: "SGS",
        link: null,
        githubLink: "https://github.com/mrshabel/sgs",
        about: "A self-hosted file server built on MinIO, complete with a modern admin UI, API keys, and project-based file organization.",
        stack: ["Go", "PostgreSQL", "MinIO", "ReactJS"],
        selected: true,
        duration: "2025",
    },
    {
        name: "SGQueue",
        link: null,
        githubLink: "https://github.com/mrshabel/sgqueue",
        about: "A lightweight, reliable postgres-based message queue with exactly-once-delivery guarantees.",
        stack: ["Go", "PostgreSQL", "Message Queues"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Chow: Local Food Compass",
        link: null,
        githubLink: "https://github.com/mrshabel/chow",
        about: "Community-driven platform built to help discover local food hot-spots, featuring user ratings and location-based search.",
        stack: ["Go", "PostGIS", "PostgreSQL", "Full Stack"],
        selected: true,
        duration: "2025",
    },
    {
        name: "Nukex",
        link: null,
        githubLink: "https://github.com/mrshabel/nukex",
        about: "A fast and interactive CLI tool to find and clean up node_modules directories consuming disk space. Provides efficient disk space management for developers.",
        stack: ["Go", "CLI", "Developer Tools"],
        selected: true,
        duration: "2025",
    },

    // secondary projects
    {
        name: "FastAPI Starter",
        link: null,
        githubLink: "https://github.com/mrshabel/fastapi-starter",
        about: "A comprehensive FastAPI template designed to improve backend development workflow with best practices, common configurations, and production-ready setup.",
        stack: [
            "Python",
            "FastAPI",
            "PostgreSQL",
            "Docker",
            "Nginx",
            "Redis",
            "Prometheus",
            "Grafana",
        ],
        selected: false,
        duration: "2025",
    },
    {
        name: "SGBank",
        link: null,
        githubLink: "https://github.com/mrshabel/sgbank",
        about: "A general ledger banking system for handling transactions between accounts, implementing financial transaction processing and account management.",
        stack: ["Go", "PostgreSQL"],
        selected: false,
        duration: "2025",
    },
    {
        name: "Chat Application",
        link: null,
        githubLink: "https://github.com/mrshabel/chat",
        about: "A real-time group chat application with room-based messaging and persistence support.",
        stack: ["Go", "WebSockets", "PostgreSQL"],
        selected: false,
        duration: "2025",
    },
    {
        name: "Ask Shabel",
        link: "https://ask-shabel.vercel.app",
        githubLink: "https://github.com/mrshabel/ask-shabel",
        about: "A chat AI application powered by OpenAI's API, featuring natural language processing, and context-aware responses",
        stack: ["NextJS", "OpenAI"],
        selected: false,
        duration: "2023 – Present",
    },
    {
        name: "Auth Service",
        link: null,
        githubLink: "https://github.com/mrshabel/auth-service",
        about: "A robust authentication service implementing JWT, OAuth2, and RBAC. Features include user management, role-based access control, and secure token handling.",
        stack: ["TypeScript", "Node.js", "Express.js", "Docker", "PostgreSQL"],
        selected: false,
        duration: "2024",
    },
    {
        name: "Notification Service",
        link: null,
        githubLink: "https://github.com/mrshabel/notification-service",
        about: "A scalable notification service built with FastAPI and RabbitMQ, supporting multiple notification channels and real-time delivery.",
        stack: ["Python", "FastAPI", "RabbitMQ", "Docker", "Nginx"],
        selected: false,
        duration: "2024",
    },
    {
        name: "Rate Limiter",
        link: null,
        githubLink: "https://github.com/mrshabel/rate-limiter",
        about: "A distributed rate limiting solution using Redis for high-performance request throttling and protection against API abuse.",
        stack: ["TypeScript", "Node.js", "Redis", "PostgreSQL", "Docker"],
        selected: false,
        duration: "2024",
    },
    {
        name: "Gorr",
        link: null,
        githubLink: "https://github.com/mrshabel/gorr",
        about: "A reverse proxy that routes HTTP requests to multiple upstream services based on URL prefix patterns.",
        stack: ["Go", "Reverse Proxy", "Load Balancing"],
        selected: false,
        duration: "2025",
    },
    {
        name: "Goncat",
        link: null,
        githubLink: "https://github.com/mrshabel/goncat",
        about: "A custom implementation of netcat utility in Go, demonstrating network programming and system-level tool development.",
        stack: ["Go", "Networking", "CLI", "System Tools"],
        selected: false,
        duration: "2024",
    },
    {
        name: "URL Shortener System",
        link: null,
        githubLink: "https://github.com/mrshabel/url-shortener",
        about: "A complete URL shortening system",
        stack: ["TypeScript", "NextJS", "ExpressJS", "PostgreSQL"],
        selected: false,
        duration: "2024",
    },
];
